---
jobs:
  include:
    - stage: test
      language: python
      python: "2.7"
      cache: pip
      services:
        - docker
      install:
        - pip install ansible
        - pip install docker-py
        - pip install molecule
      script: molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
