- name: Copy templates
  template:
    src: templates/{{ item.src }}
    dest: /opt/docker-healthchecks/{{ item.dest }}
    owner: root
    group: root
    mode: '0400'
  with_items:
    - src: app.conf.j2
      dest: nginx/config/app.conf
    - src: app.env.j2
      dest: app/app.env
    - src: db.env.j2
      dest: db/db.env
    - src: local_settings.py.j2
      dest: app/config/local_settings.py
    - src: passphrase.j2
      dest: backups/passphrase
    - src: config.yaml.j2
      dest: backups/config.yaml

- name: Create directories
  file:
    path: /opt/docker-healthchecks/{{ item.path }}
    owner: root
    group: root
    mode: '0400'
    state: directory
  with_items:
    - path: ssh

- name: Copy files
  copy:
    src: files/{{ item.src }}
    dest: /opt/docker-healthchecks/{{ item.dest }}
    owner: root
    group: root
    mode: '0400'
  with_items:
    - src: id_rsa
      dest: backups/ssh/id_rsa
    - src: id_rsa.pub
      dest: backups/ssh/id_rsa.pub
    - src: known_hosts
      dest: backups/ssh/known_hosts

- name: Start app
  docker_service:
    project_src: /opt/docker-healthchecks
    pull: true
    state: present
  # can't start docker containers within docker containers
  when: not hc__testing
  notify: disable backups
