---
- name: Converge
  hosts: all
  vars:
    - hc__backup_passphrase: secure
    - hc__borg_repo_url: user@example.org:repo
    - hc__db_password: test
    - hc__email_from: test@example.org
    - hc__email_host: example.org
    - hc__email_password: test
    - hc__hostname: http://example.org
    - hc__su_email: test@example.org
    - hc__su_password: test
    - hc__su_username: test
    - hc__testing: true
  roles:
    - role: ansible-role-healthchecks
