---
- name: Converge
  hosts: all
  vars:
    - hc__backup_passphrase: secure
    - hc__db_password: test
    - hc__email_from: test@example.org
    - hc__email_host: example.org
    - hc__email_password: test
    - hc__hostname: http://example.org
    - hc__su_email: test@example.org
    - hc__su_password: test
    - hc__su_username: test
  pre_tasks:
    - name: Install pip
      package:
        name: python-pip
        state: present

    - name: Install pip deps
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker-py
        - docker-compose
  roles:
    - role: ansible-role-healthchecks
